# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2716b8df8b536221093bf736164aabd23139f23038f3588807b88a677f0eddefed496a7a72b16f1b38b1a13440b5057320e3fc8f26f1d7414f6b6ae08b226dd

test:
  secret_key_base: bb48a663dd24b85122d953287d28b84f32364c869ea60eb3b30138471783e0a9af19e146593c1d621ff6637cdbc5a1714097d310e2e047af41b5f4ac24290eac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
